---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ovs-cni-plugin-installator-amd64
  namespace: kube-system
  labels:
    tier: node
    app: ovs-cni-plugin
spec:
  template:
    metadata:
      labels:
        tier: node
        app: ovs-cni-plugin
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: ovs-cni-plugin-installator
        image: registry:5000/ovs-cni-plugin
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
